User.destroy_all

u1 = User.create name: "Linna", email: "linna@ga.co", password: "chicken", image: "/assets/bg.jpeg"
u2 = User.create name: "Bob", email: "bob@ga.co", password: "chicken", image: "/assets/bg.jpeg"
u3 = User.create name: "Patrick", email: "patrick@ga.co", password: "chicken", image: "/assets/bg.jpeg"

puts "#{User.all.length} users"

Cuisine.destroy_all

c1 = Cuisine.create name: "Afghani"
c2 = Cuisine.create name: "African"
c3 = Cuisine.create name: "American"
c4 = Cuisine.create name: "Arabian"
c5 = Cuisine.create name: "Argentine"
c6 = Cuisine.create name: "Asian"
c7 = Cuisine.create name: "Australian"
c8 = Cuisine.create name: "Austrian"
c9 = Cuisine.create name: "BBQ"
c10 = Cuisine.create name: "Bakery"
c11 = Cuisine.create name: "Bangladeshi"
c12 = Cuisine.create name: "Bar Food"
c14 = Cuisine.create name: "Basque"
c15 = Cuisine.create name: "Belgian"
c16 = Cuisine.create name: "Beverages"
c17 = Cuisine.create name: "Brasserie"
c18 = Cuisine.create name: "Brazilian"
c19 = Cuisine.create name: "British"
c20 = Cuisine.create name: "Bubble Tea"
c21 = Cuisine.create name: "Burger"
c22 = Cuisine.create name: "Burmese"
c23 = Cuisine.create name: "Cafe"
c26 = Cuisine.create name: "Cambodian"
c27 = Cuisine.create name: "Cantonese"
c28 = Cuisine.create name: "Caribbean"
c29 = Cuisine.create name: "Charcoal"
c30 = Cuisine.create name: "Chicken"
c31 = Cuisine.create name: "Chinese"
c32 = Cuisine.create name: "Coffee"
c34 = Cuisine.create name: "Colombian"
c35 = Cuisine.create name: "Contemporary"
c36 = Cuisine.create name: "Continental"
c37 = Cuisine.create name: "Creole"
c38 = Cuisine.create name: "Crepes"
c39 = Cuisine.create name: "Croatian"
c40 = Cuisine.create name: "Cuban"
c41 = Cuisine.create name: "Czech"
c42 = Cuisine.create name: "Danish"
c43 = Cuisine.create name: "Deli"
c44 = Cuisine.create name: "Desserts"
c45 = Cuisine.create name: "Diner"
c48 = Cuisine.create name: "Dumplings"
c49 = Cuisine.create name: "Dutch"
c50 = Cuisine.create name: "Eastern"
c51 = Cuisine.create name: "European"
c52 = Cuisine.create name: "Egyptian"
c54 = Cuisine.create name: "Ethiopian"
c55 = Cuisine.create name: "European"
c56 = Cuisine.create name: "Falafel"
c57 = Cuisine.create name: "Filipino"
c58 = Cuisine.create name: "Finger Food"
c60 = Cuisine.create name: "Fish and Chips"
c63 = Cuisine.create name: "French"
c64 = Cuisine.create name: "Fried Chicken"
c66 = Cuisine.create name: "Frozen"
c67 = Cuisine.create name: "Yogurt"
c68 = Cuisine.create name: "Fusion"
c69 = Cuisine.create name: "German"
c70 = Cuisine.create name: "Greek"
c71 = Cuisine.create name: "Grill"
c72 = Cuisine.create name: "Hawaiian"
c73 = Cuisine.create name: "Healthy"
c74 = Cuisine.create name: "Hot Pot"
c75 = Cuisine.create name: "Hungarian"
c76 = Cuisine.create name: "Ice Cream"
c78 = Cuisine.create name: "Indian"
c79 = Cuisine.create name: "Indonesian"
c80 = Cuisine.create name: "International"
c81 = Cuisine.create name: "Iranian"
c82 = Cuisine.create name: "Iraqi"
c83 = Cuisine.create name: "Irish"
c84 = Cuisine.create name: "Israeli"
c85 = Cuisine.create name: "Italian"
c86 = Cuisine.create name: "Japanese"
c87 = Cuisine.create name: "Jewish"
c88 = Cuisine.create name: "Juices"
c89 = Cuisine.create name: "Kebab"
c90 = Cuisine.create name: "Kiwi"
c91 = Cuisine.create name: "Korean"
c94 = Cuisine.create name: "Laotian"
c95 = Cuisine.create name: "Latin"
c96 = Cuisine.create name: "American"
c97 = Cuisine.create name: "Lebanese"
c98 = Cuisine.create name: "Malaysian"
c99 = Cuisine.create name: "Mediterranean"
c100 = Cuisine.create name: "Mexican"
c101 = Cuisine.create name: "Middle Eastern"
c102 = Cuisine.create name: "Mongolian"
c103 = Cuisine.create name: "Moroccan"
c104 = Cuisine.create name: "Nepalese"
c105 = Cuisine.create name: "North Indian"
c106 = Cuisine.create name: "Oriental"
c107 = Cuisine.create name: "Pakistani"
c108 = Cuisine.create name: "Pan"
c109 = Cuisine.create name: "Pastry"
c110 = Cuisine.create name: "Patisserie"
c111 = Cuisine.create name: "Peruvian"
c112 = Cuisine.create name: "Pho"
c113 = Cuisine.create name: "Pizza"
c114 = Cuisine.create name: "Poké"
c115 = Cuisine.create name: "Polish"
c116 = Cuisine.create name: "Portuguese"
c117 = Cuisine.create name: "Pub"
c118 = Cuisine.create name: "Ramen"
c119 = Cuisine.create name: "Roast"
c120 = Cuisine.create name: "Russian"
c121 = Cuisine.create name: "Salad"
c122 = Cuisine.create name: "Sandwich"
c123 = Cuisine.create name: "Satay"
c124 = Cuisine.create name: "Scandinavian"
c125 = Cuisine.create name: "Seafood"
c126 = Cuisine.create name: "Shanghai"
c127 = Cuisine.create name: "Sichuan"
c128 = Cuisine.create name: "Singaporean"
c129 = Cuisine.create name: "South Indian"
c130 = Cuisine.create name: "Spanish"
c131 = Cuisine.create name: "Sri Lankan"
c132 = Cuisine.create name: "Steak"
c133 = Cuisine.create name: "Street Food"
c135 = Cuisine.create name: "Sushi"
c136 = Cuisine.create name: "Swedish"
c137 = Cuisine.create name: "Swiss"
c138 = Cuisine.create name: "Taiwanese"
c139 = Cuisine.create name: "Tapas"
c140 = Cuisine.create name: "Tea"
c141 = Cuisine.create name: "Teppanyaki"
c142 = Cuisine.create name: "Teriyaki"
c143 = Cuisine.create name: "Tex-Mex"
c144 = Cuisine.create name: "Thai"
c145 = Cuisine.create name: "Tibetan"
c146 = Cuisine.create name: "Turkish"
c147 = Cuisine.create name: "Turkish"
c148 = Cuisine.create name: "Pizza"
c149 = Cuisine.create name: "Ukrainian"
c150 = Cuisine.create name: "Uruguayan"
c151 = Cuisine.create name: "Uyghur"
c152 = Cuisine.create name: "Vegan"
c153 = Cuisine.create name: "Vegetarian"
c154 = Cuisine.create name: "Venezuelan"
c155 = Cuisine.create name: "Vietnamese"
c156 = Cuisine.create name: "Yum Cha"

puts "#{Cuisine.all.length} cuisines"

Restaurant.destroy_all

re1 = Restaurant.create name: "Est.", address: "Level 1, Establishment, 252 George Street, CBD, Sydney, NSW", open_hrs: "12noon – 2:30pm, 6pm – 10pm", cost_two: 320, phone:"+61291147312", image:"/assets/est.jpg", year:2013, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."



re2 = Restaurant.create name: "Momofuku Seiōbo", address: "80 Pyrmont Street, The Star, Pyrmont, Pyrmont, Sydney", open_hrs: "6:30pm – 10pm", cost_two: 370, phone:"+61296579169", image:"/assets/momofuku.jpg", year:2019, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."

re3 = Restaurant.create name: "Quay", address: "Upper Level, Overseas Passenger Terminal 5 Hickson Road, The Rocks, Sydney, NSW", open_hrs: "6pm – 10pm", cost_two: 500, phone:"+61292515600", image:"/assets/quay.jpg", year:2019, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."

re4 = Restaurant.create name: "Rockpool", address: "66 Hunter Street, CBD, Sydney, NSW", open_hrs: "6pm – 10pm", cost_two: 150, phone:"+61280781900", image:"/assets/rockpool.jpg", year:2016, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."

re5 = Restaurant.create name: "Sepia", address: "Darling Park, 201 Sussex Street, Darling Harbour, Sydney", open_hrs: "6pm – 10pm", cost_two: 500, phone:"+61292831990", image:"/assets/sepia.jpg", year:2019, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."

re6 = Restaurant.create name: "The Bridge Room", address: "Ground Level, 44 Bridge Street, Circular Quay, Sydney", open_hrs: "12noon – 3pm, 6pm – 10pm", cost_two: 150, phone:"+61292477000", image:"/assets/bridge_room.jpg", year:2017, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."

re7 = Restaurant.create name: "Sixpenny", address: "83 Percival Rd, Stanmore", open_hrs: "6pm – 10pm", cost_two: 280, phone:"+61295726666", image:"/assets/sixpenny.jpg", year: 2019, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."

re8 = Restaurant.create name: "Tetsuya's", address: "529 Kent Street, CBD, Sydney, NSW", open_hrs: "6pm – 10pm", cost_two: 440, phone:"+61292672900", image:"/assets/tetsuya.png", year: 2010, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat lacus, maximus id volutpat sagittis, cursus id justo. Cras blandit risus eget pellentesque molestie. Sed volutpat orci at neque finibus vestibulum. Morbi magna lectus, semper sed interdum ac, posuere quis orci. Morbi ultricies diam ac mi fermentum tempus. Vestibulum sapien urna, commodo eu dolor vel, commodo blandit eros. Mauris non metus bibendum, accumsan augue a, ullamcorper quam."




puts "#{Restaurant.all.length} restaurants"

re1.cuisines << c140 << c32 << c23
re2.cuisines << c118 << c86 << c6
re3.cuisines << c126 << c6 << c48
re4.cuisines << c135

Review.destroy_all

r1 = Review.create content: "It was really good.", rating: 3, user_id: u1.id, restaurant_id: re1.id, image: "http://placekitten.com/250/250"

r2 = Review.create content: "Amazing! Had an excellent time", rating: 4, user_id: u3.id, restaurant_id: re2.id, image: "http://placekitten.com/250/250"

r3 = Review.create content: "It was really bad!! Never coming again!", rating: 1, user_id: u2.id, restaurant_id: re2.id, image: "http://placekitten.com/250/250"

r4 = Review.create content: "It was really good!! Always coming again!", rating: 5, user_id: u2.id, restaurant_id: re3.id, image: "http://placekitten.com/250/250"

puts "#{Review.all.length} reviews"
